name: Retrain Model

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to v4 to support Node.js 20

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to v4 to support Node.js 20
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r recommendation-system/utils/requirements.txt

      - name: Run train_model.py
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}  # Using the secret
        run: |
          python recommendation-system/utils/train_model.py

      - name: Commit and push the model
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add recommendation-system/flask_app/model/nmf_model.pkl
          git commit -m 'Retrained model'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Provided by GitHub Actions


  
         
